
import 'package:appwrite/appwrite.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:get_receipt/helpers/weekly_report.dart';
import 'package:get_receipt/pages/account_page.dart';
import 'package:get_receipt/pages/auth_page.dart';
import 'package:get_receipt/pages/clients_page.dart';
import 'package:get_receipt/pages/error_page.dart';
import 'package:get_receipt/pages/field_input_page.dart';
import 'package:get_receipt/pages/history_page.dart';
import 'package:get_receipt/pages/home_page.dart';
import 'package:get_receipt/pages/home_pending_page.dart';
import 'package:get_receipt/pages/home_withholding_page.dart';
import 'package:get_receipt/pages/qr_scan_page.dart';
import 'package:get_receipt/pages/setting.dart';
import 'package:get_receipt/pages/splash_page.dart';
import 'package:get_receipt/services/log_in_service.dart';
import 'package:get_receipt/services/mainservice.dart';
import 'package:get_receipt/services/withholding_service.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI (optional)

import 'helpers/expense_summery.dart';
import 'helpers/utils.dart';
import 'security/device_security.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

Client client = Client();

const bool isProduction = bool.fromEnvironment('dart.vm.product');
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
FlutterLocalNotificationsPlugin();

/// 🔹 BACKGROUND HANDLER (REQUIRED)
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
}
class NotificationService {
  final FirebaseMessaging _messaging = FirebaseMessaging.instance;

  Future<void> init() async {
    // 🔹 Local notification init
    const androidInit = AndroidInitializationSettings('@drawable/ic_notification');
    const iosInit = DarwinInitializationSettings();

    const initSettings = InitializationSettings(
      android: androidInit,
      iOS: iosInit,
    );

    await flutterLocalNotificationsPlugin.initialize(initSettings);

    // 🔹 iOS permission
    await _messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
    );

    // 🔹 iOS foreground display fix
    await FirebaseMessaging.instance
        .setForegroundNotificationPresentationOptions(
      alert: true,
      badge: true,
      sound: true,
    );

    // 🔹 Get token
    String? token = await _messaging.getToken();

    /// 🔹 FOREGROUND
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      final notification = message.notification;
      if (notification != null) {
        _showLocalNotification(notification.title, notification.body);
      }
    });

    /// 🔹 CLICK (BACKGROUND → OPEN)
    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      Utils.mainAppNav.currentState?.pushNamed('/welcomepage');
    });
  }

  void _showLocalNotification(String? title, String? body) {
    const androidDetails = AndroidNotificationDetails(
      'default_channel',
      'Default',
      importance: Importance.max,
      priority: Priority.high,
      icon: '@drawable/ic_notification',
    );

    const iosDetails = DarwinNotificationDetails();

    const details = NotificationDetails(
      android: androidDetails,
      iOS: iosDetails,
    );

    final id = DateTime.now().millisecondsSinceEpoch ~/ 1000;

    flutterLocalNotificationsPlugin.show(
      id,
      title,
      body,
      details,
    );
  }
}
void main() async  {
  WidgetsFlutterBinding.ensureInitialized();
  final compromised =
  await DeviceSecurity.isDeviceCompromised();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  // Request permissions (iOS mainly)
  NotificationSettings settings =
  await FirebaseMessaging.instance.requestPermission();
  client
      .setEndpoint('https://app.getrestt.com/v1') //https://172.31.228.216
      .setProject('64020bea5f7df43b0cfe');  //64020bea5f7df43b0cfe //68e8c3aa000b425d0f23
      //.setSelfSigned(status: true); // For self signed certificates, only use for development

  if (isProduction) {
    debugPrint = (String? message, {int? wrapWidth}) => null;
  }

  runApp(
      compromised ? const BlockedApp() :
      MultiProvider(
          providers: [
             ChangeNotifierProvider(
                create: (_) => LoginService()
            ),
            /*
            ChangeNotifierProvider(
                create: (_) => CategorySelectionService()
            ),*/
            Provider(
                create: (_) => MainService()
            ),
            Provider(
                create: (_) => WithholdingService()
            ),
            Provider(
                create: (_) => UserInfoService()
            ),
            Provider(
                create: (_) => ExpenseSummery()
            ),
            Provider(
                create: (_) => WeeklyExpenseReport()
            ),


          ],
          child: MyApp(),
      )
  );
}
class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  void initState() {
    super.initState();

    /// 🔹 INIT NOTIFICATIONS
    Future.microtask(() =>
        Provider.of<NotificationService>(context, listen: false).init());
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Get Receipt",
      theme: ThemeData(
        primaryColor: Colors.green,
        colorScheme: ColorScheme.fromSwatch(
          primarySwatch: Colors.green,
        ),
      ),
      navigatorKey: Utils.mainAppNav,
      debugShowCheckedModeBanner: false,
      initialRoute: '/',
      routes: {
        '/': (context) => Splash(duration: 2, goToPage: '/welcomepage'),
        '/welcomepage': (context) => Home(),
        '/auth': (context) => Auth(),
        '/setting': (context) => Setting(),
        '/homePending': (context) => HomePending(),
        '/withholding': (context) => HomeWithholding(),
        '/account': (context) => AccountPage(),
        '/ErrorPage': (context) => ErrorPage(),
        '/history': (context) => History(),
        '/client': (context) => ClientsPage(),
        //'/qr_code_scan': (context) => QrCodeScan(),//
        /*
              '/detailspage': (context) => DetailsPage(),
              '/mappage': (context) => MapPage(),
              '/onboardingpage': (context) => OnboardingPage(),*/
      },

    );
  }
}

class BlockedApp extends StatelessWidget {
  const BlockedApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text(
            'This device is not supported for security reasons.',
            textAlign: TextAlign.center,
          ),
        ),
      ),
    );
  }
}

